[theme]
primaryColor = "#2EC4B6"
backgroundColor = "#1b4f72"
secondaryBackgroundColor = "#1f7a8c"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true